language: crystal

crystal:
  - latest
  - nightly

services:
  - postgresql
  - redis-server

cache:
  directories:
    - bin
    - lib
    - .shards

env:
  - TEST_SUITE=./spec/mochi

script:
  - crystal tool format --check
  - crystal bin/ameba.cr
  - crystal spec/sam.cr -- db:migrate
  - crystal spec --order random --error-on-warnings
  - crystal docs


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  project_name: mochi
  on:
    branch: master
  local_dir: docs
