dist: bionic
sudo: required
language: crystal

services:
  - postgresql
  - redis-server

cache:
  directories:
    - bin
    - lib
    - .shards

env:
  - TEST_SUITE=./spec/mochi

script:
  - crystal spec/sam.cr -- db:migrate
  - crystal spec
